apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  selector:
    matchLabels:
      app: history
  template:
    spec:
      containers:
        - name: history
          image: $CONTAINER_REGISTRY/prod-history:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
              cpu: "100m"