apiVersion: v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  selector:
    matchLabels:
      app: video-streaming
  template:
    spec:
      containers:
        - name: video-streaming
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
              cpu: "100m"