apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  selector:
    matchLabels:
      app: video-streaming
  template:
    spec:
      containers:
        - name: video-streaming
          image: $CONTAINER_REGISTRY/video-streaming:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
              cpu: "100m"