apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-upload
spec:
  selector:
    matchLabels:
      app: video-upload
  template:
    spec:
      containers:
        - name: video-upload
          image: $CONTAINER_REGISTRY/prod-video-upload:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
              cpu: "100m"
