apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/video-storage
- ../../base/history
- ../../base/video-streaming

patches:
  - path: history-deployment-patch.yaml
  - path: video-streaming-deployment-patch.yaml
  - path: video-storage-deployment-patch.yaml
