apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/video-storage
- ../../base/history
- ../../base/video-streaming

patches:
  - path: history-patch-resources.yaml
  - path: video-streaming-patch-resources.yaml
  - path: azure-storage-patch-resources.yaml
