include:
  - ./docker-compose-mongodb.yml
services:
  db-fixture-rest-api:
    image: db-fixture-rest-api
    build:
      context: .
    container_name: db-fixture-rest-api
    ports:
      - "9000:${PORT}"
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_FIXTURES_HOST=${DB_FIXTURES_HOST}
      - FIXTURES_DIR=${FIXTURES_DIR}
      - PORT=${PORT}
    restart: "always"
