include:
  - ./docker-compose-gateway.yml
  - ./docker-compose-video-streaming-prod.yml
  - ./docker-compose-metadata-prod.yml
services:
  gateway:
    build:
      dockerfile: apps/gateway/Dockerfile-prod
