include:
  - ./docker-compose-video-streaming.yml
  - ./docker-compose-video-storage-prod.yml
  - ./docker-compose-history-prod.yml
services:
  video-streaming:
    build:
      dockerfile: apps/video-streaming/Dockerfile-prod
    