include:
  - ./docker-compose-db-fixture-rest-api.yml
services:
  db-fixture-rest-api:
    build:
      dockerfile: apps/db-fixture-rest-api/Dockerfile-dev
    volumes:
      - ./:/app:z
      - /app/node_modules
      - /app/.nx
