services:
  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"
  
  rabbit:
    image: rabbitmq:4.2.2-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: "always"
