services:
  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: "always"

  azure-storage:
    image: azure-storage
    build:
      context: .
      dockerfile: apps/azure-storage/Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: .
      dockerfile: apps/video-streaming/Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    depends_on:
      - db
      - azure-storage
    environment:
      - PORT=80
      - DBHOST=${DBHOST}
      - DBNAME=${DBNAME}
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
