include:
  - docker-compose-video-upload.yml
  - docker-compose-video-storage-dev.yml
services:
  video-upload:
    build:
      dockerfile: apps/video-upload/Dockerfile-dev
    volumes:
      - ./:/app:z
      - /app/node_modules
      - /app/.nx
