include:
  - ./docker-compose-gateway.yml
  - ./docker-compose-video-streaming-dev.yml
  - ./docker-compose-metadata-dev.yml
services:
  gateway:
    build:
      dockerfile: apps/gateway/Dockerfile-dev
    volumes:
      - ./:/app:z
      - /app/node_modules
      - /app/.nx
