apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-fixture-rest-api
spec:
  selector:
    matchLabels:
      app: db-fixture-rest-api
  template:
    spec:
      containers:
        - name: db-fixture-rest-api
          image: $CONTAINER_REGISTRY/staging-db-fixture-rest-api:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"
