apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: staging
spec:
  selector:
    matchLabels:
      app: history
  template:
    spec:
      containers:
        - name: history
          image: $CONTAINER_REGISTRY/staging-history:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"