apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage
  namespace: staging
spec:
  selector:
    matchLabels:
      app: video-storage
  template:
    spec:
      containers:
        - name: video-storage
          image: $CONTAINER_REGISTRY/staging-video-storage:$VERSION
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"