apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
    spec:
      containers:
        - name: video-upload
          image: video-upload:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: video-upload-config
                  key: port
            - name: RABBIT
              valueFrom:
                configMapKeyRef:
                  name: video-upload-config
                  key: rabbit
            - name: VIDEO_STORAGE_HOST
              valueFrom:
                configMapKeyRef:
                  name: video-upload-config
                  key: videoStorageHost
