apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: video-streaming:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: video-streaming-config
                  key: port
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: video-streaming-config
                  key: dbHost
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: video-streaming-config
                  key: dbName
            - name: RABBIT
              valueFrom:
                configMapKeyRef:
                  name: video-streaming-config
                  key: rabbit 
