apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: qa
spec:
  selector:
    matchLabels:
      app: history
  template:
    spec:
      containers:
        - name: history
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"