apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage
  namespace: qa
spec:
  selector:
    matchLabels:
      app: video-storage
  template:
    spec:
      containers:
        - name: video-storage
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "128Mi"
              cpu: "100m"