apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: metadata:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: metadata-config
                  key: port
            - name: METADATA_DBHOST
              valueFrom:
                configMapKeyRef:
                  name: metadata-config
                  key: metadataDbHost
            - name: METADATA_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: metadata-config
                  key: metadataDbName
            - name: RABBIT
              valueFrom:
                configMapKeyRef:
                  name: metadata-config
                  key: rabbit
